tools:
    php_cs_fixer: true
    php_mess_detector: true
    sensiolabs_security_checker: true

    php_code_sniffer:
        config:
            standard: PSR2

    php_analyzer:
        config:
            # Prevent calls to isolator, and test fixtures from being flagged.
            typo_checks:
                enabled: false
