sudo: false
language: php

php: ["5.3", "5.4", "5.5", "5.6", "7.0", "hhvm"]

matrix:
    allow_failures: [{"php": "7.0"}, {"php": "hhvm"}]
    fast_finish: true

    # Include another build in the matrix for dogfooding Archer!
    include:
        - php: "5.6"
          env:
            - secure: "p/oUz8YI/1zK181nm8wY+hims2obPit4U6VU2sMqZ/i094vD4EwStx2ELaLLp8QrxNF4ScYr7PTqpZFfgZgHUh1n06IRx63P4YGWPt6LIVnc0gl9WuffVQXJt1wBysRjhQGWL07XTwhpFn6iCwamxEMgGGZba8ghB94RA+iMzLI="

install:
  - ./.archer/travis.install

script:
  - ./.archer/travis.build
