language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

install:
    - composer install --dev --prefer-dist --no-interaction
script:
    - phpunit

matrix:
  # PHP 5.5 is still in alpha, so ignore build failures.
  allow_failures:
    - php: 5.5
